-- Sync PostgreSQL enum types to match canonical models.py

-- JobStatus enum
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'VALIDATED';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'READY';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'CLAIMING';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'DECLINED';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'DISPATCHING';
ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'CANCELLED';

-- EventType enum
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'JOB_VALIDATED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SCHEDULE_PROPOSED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'APPROVAL_GRANTED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'APPROVAL_DECLINED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'DISPATCH_REQUESTED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'DISPATCH_BLOCKED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'DISPATCH_STARTED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'DISPATCH_AUTHORIZED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'JOB_CANCELLED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AUTH_LOGIN_SUCCESS';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AUTH_LOGIN_FAILURE';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AUTH_ACCESS_DENIED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AUTH_USER_REGISTERED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AUTH_USER_ACTIVATED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AUTH_USER_DEACTIVATED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'CONFIG_CHANGED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'TENANT_CREATED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'API_KEY_CREATED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'API_KEY_REVOKED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'AUDIT_VERIFICATION_FAILED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'JOB_RESUBMITTED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SCHEDULING_FAILED';
ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'EMAIL_DELIVERY_FAILED';
